import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from cli import utils as cli_utils
from cli.config import Config

TEMPLATE = (
    PROJECT_ROOT / "server" / "traefik" / "traefik.prod.template.yml"
)
HEADER_LINE = "# Auto-generated by P-BitM CLI; contains paths, not secret values."


class EnsureDnsChallengeTests(unittest.TestCase):
    """ensure_dns_challenge() must support TLS-ALPN-01 (ssl.acme_challenge:
    tlsalpn) without DNS provider credentials, while the default DNS-01 path
    stays behaviorally identical. The project root is redirected to a temp
    copy so the real server/ tree is never touched."""

    def _run(self, config_yaml, env=None):
        tmp_root = Path(tempfile.mkdtemp(prefix="pbitm-acme-test-"))
        (tmp_root / "cli").mkdir()
        (tmp_root / "server" / "traefik").mkdir(parents=True)
        shutil.copy(TEMPLATE, tmp_root / "server" / "traefik" / TEMPLATE.name)

        config_path = tmp_root / "config.yaml"
        config_path.write_text(config_yaml)

        with patch.object(
            cli_utils, "__file__", str(tmp_root / "cli" / "utils.py")
        ), patch.object(
            cli_utils, "config", Config(config_path)
        ), patch.object(
            cli_utils, "adopt_generated_path", lambda path: None
        ), patch.dict(os.environ, env or {}):
            result = cli_utils.ensure_dns_challenge()

        runtime_path = (
            tmp_root / "server" / "traefik" / "traefik.prod.runtime.yml"
        )
        dns_env_path = tmp_root / "server" / ".traefik-dns.env"
        runtime = (
            yaml.safe_load(runtime_path.read_text())
            if runtime_path.exists()
            else None
        )
        dns_env = dns_env_path.read_text() if dns_env_path.exists() else None
        return result, runtime, dns_env, tmp_root

    def _acme(self, runtime):
        return runtime["certificatesResolvers"]["letsencrypt"]["acme"]

    def _assert_dns_mode(self, runtime, dns_env, tmp_root):
        acme = self._acme(runtime)
        self.assertEqual(acme["email"], "admin@example.com")
        self.assertEqual(acme["storage"], "/letsencrypt/acme.json")
        self.assertEqual(acme["dnsChallenge"]["provider"], "duckdns")
        self.assertNotIn("tlsChallenge", acme)
        self.assertIn("DUCKDNS_TOKEN_FILE=/run/secrets/dns/DUCKDNS_TOKEN", dns_env)
        secret = tmp_root / "server" / ".secrets" / "dns" / "DUCKDNS_TOKEN"
        self.assertEqual(secret.read_text(), "token-value\n")

    DNS_CONFIG = (
        "ssl:\n"
        "  acme_email: \"admin@example.com\"\n"
        "  dns_challenge:\n"
        "    provider: \"duckdns\"\n"
        "    credentials: [\"DUCKDNS_TOKEN\"]\n"
        "    environment: {}\n"
    )

    def test_dns_mode_unchanged(self):
        result, runtime, dns_env, tmp_root = self._run(
            "ssl:\n"
            "  acme_email: \"admin@example.com\"\n"
            "  acme_challenge: \"dns\"\n"
            "  dns_challenge:\n"
            "    provider: \"duckdns\"\n"
            "    credentials: [\"DUCKDNS_TOKEN\"]\n"
            "    environment: {}\n",
            env={"DUCKDNS_TOKEN": "token-value"},
        )
        self.assertTrue(result)
        self._assert_dns_mode(runtime, dns_env, tmp_root)

    def test_absent_acme_challenge_defaults_to_dns(self):
        result, runtime, dns_env, tmp_root = self._run(
            self.DNS_CONFIG, env={"DUCKDNS_TOKEN": "token-value"}
        )
        self.assertTrue(result)
        self._assert_dns_mode(runtime, dns_env, tmp_root)

    def test_tlsalpn_mode_skips_credentials_and_swaps_challenge(self):
        # Placeholder provider/credentials would fail DNS-mode validation;
        # tlsalpn must ignore them entirely.
        result, runtime, dns_env, tmp_root = self._run(
            "ssl:\n"
            "  acme_email: \"admin@example.com\"\n"
            "  acme_challenge: \"tlsalpn\"\n"
            "  dns_challenge:\n"
            "    provider: \"<DNS_PROVIDER>\"\n"
            "    credentials: [\"<PROVIDER_REQUIRED_ENV_VAR>\"]\n"
        )
        self.assertTrue(result)

        acme = self._acme(runtime)
        self.assertEqual(acme["email"], "admin@example.com")
        self.assertEqual(acme["storage"], "/letsencrypt/acme.json")
        self.assertIs(acme["tlsChallenge"], True)
        self.assertNotIn("dnsChallenge", acme)

        self.assertEqual(dns_env, HEADER_LINE + "\n")
        self.assertFalse((tmp_root / "server" / ".secrets").exists())

    def test_invalid_acme_email_rejected_in_dns_mode(self):
        result, runtime, _, _ = self._run(
            "ssl:\n"
            "  acme_email: \"not-an-email\"\n"
            "  dns_challenge:\n"
            "    provider: \"duckdns\"\n"
            "    credentials: []\n"
        )
        self.assertFalse(result)
        self.assertIsNone(runtime)

    def test_invalid_acme_email_rejected_in_tlsalpn_mode(self):
        result, runtime, _, _ = self._run(
            "ssl:\n"
            "  acme_email: \"not-an-email\"\n"
            "  acme_challenge: \"tlsalpn\"\n"
        )
        self.assertFalse(result)
        self.assertIsNone(runtime)

    def test_invalid_acme_challenge_rejected(self):
        result, runtime, _, _ = self._run(
            "ssl:\n"
            "  acme_email: \"admin@example.com\"\n"
            "  acme_challenge: \"http\"\n"
        )
        self.assertFalse(result)
        self.assertIsNone(runtime)


if __name__ == "__main__":
    unittest.main()
